---
title: 'Emo APIs Analysis'
author: 'Mohamed'
date: '2017'
output: html_document
---
---
output:
  html_document: default
  pdf_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(ggplot2)
library(grid)
library(gridExtra)

## Gives count, mean, standard deviation, standard error of the mean, and confidence interval (default 95%).
##   data: a data frame.
##   measurevar: the name of a column that contains the variable to be summariezed
##   groupvars: a vector containing names of columns that contain grouping variables
##   na.rm: a boolean that indicates whether to ignore NA's
##   conf.interval: the percent range of the confidence interval (default is 95%)
summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
                      conf.interval=.95, .drop=TRUE) {
    library(plyr)

    # New version of length which can handle NA's: if na.rm==T, don't count them
    length2 <- function (x, na.rm=FALSE) {
        if (na.rm) sum(!is.na(x))
        else       length(x)
    }

    # This does the summary. For each group's data frame, return a vector with
    # N, mean, and sd
    datac <- ddply(data, groupvars, .drop=.drop,
      .fun = function(xx, col) {
        c(N    = length2(xx[[col]], na.rm=na.rm),
          mean = mean   (xx[[col]], na.rm=na.rm),
          sd   = sd     (xx[[col]], na.rm=na.rm)
        )
      },
      measurevar
    )

    # Rename the 'mean' column    
    datac <- rename(datac, c('mean' = measurevar))

    datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean

    # Confidence interval multiplier for standard error
    # Calculate t-statistic for confidence interval: 
    # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
    ciMult <- qt(conf.interval/2 + .5, datac$N-1)
    datac$ci <- datac$se * ciMult

    return(datac)
}

## Norms the data within specified groups in a data frame; it normalizes each
## subject (identified by idvar) so that they have the same mean, within each group
## specified by betweenvars.
##   data: a data frame.
##   idvar: the name of a column that identifies each subject (or matched subjects)
##   measurevar: the name of a column that contains the variable to be summariezed
##   betweenvars: a vector containing names of columns that are between-subjects variables
##   na.rm: a boolean that indicates whether to ignore NA's
normDataWithin <- function(data=NULL, idvar, measurevar, betweenvars=NULL,
                           na.rm=FALSE, .drop=TRUE) {
    library(plyr)

    # Measure var on left, idvar + between vars on right of formula.
    data.subjMean <- ddply(data, c(idvar, betweenvars), .drop=.drop,
     .fun = function(xx, col, na.rm) {
        c(subjMean = mean(xx[,col], na.rm=na.rm))
      },
      measurevar,
      na.rm
    )

    # Put the subject means with original data
    data <- merge(data, data.subjMean)

    # Get the normalized data in a new column
    measureNormedVar <- paste(measurevar, '_norm', sep='')
    data[,measureNormedVar] <- data[,measurevar] - data[,'subjMean'] +
                               mean(data[,measurevar], na.rm=na.rm)

    # Remove this subject mean column
    data$subjMean <- NULL

    return(data)
}

## Summarizes data, handling within-subjects variables by removing inter-subject variability.
## It will still work if there are no within-S variables.
## Gives count, un-normed mean, normed mean (with same between-group mean),
##   standard deviation, standard error of the mean, and confidence interval.
## If there are within-subject variables, calculate adjusted values using method from Morey (2008).
##   data: a data frame.
##   measurevar: the name of a column that contains the variable to be summariezed
##   betweenvars: a vector containing names of columns that are between-subjects variables
##   withinvars: a vector containing names of columns that are within-subjects variables
##   idvar: the name of a column that identifies each subject (or matched subjects)
##   na.rm: a boolean that indicates whether to ignore NA's
##   conf.interval: the percent range of the confidence interval (default is 95%)
summarySEwithin <- function(data=NULL, measurevar, betweenvars=NULL, withinvars=NULL,
                            idvar=NULL, na.rm=FALSE, conf.interval=.95, .drop=TRUE) {

  # Ensure that the betweenvars and withinvars are factors
  factorvars <- vapply(data[, c(betweenvars, withinvars), drop=FALSE],
    FUN=is.factor, FUN.VALUE=logical(1))

  if (!all(factorvars)) {
    nonfactorvars <- names(factorvars)[!factorvars]
    message('Automatically converting the following non-factors to factors: ',
            paste(nonfactorvars, collapse = ', '))
    data[nonfactorvars] <- lapply(data[nonfactorvars], factor)
  }

  # Get the means from the un-normed data
  datac <- summarySE(data, measurevar, groupvars=c(betweenvars, withinvars),
                     na.rm=na.rm, conf.interval=conf.interval, .drop=.drop)

  # Drop all the unused columns (these will be calculated with normed data)
  datac$sd <- NULL
  datac$se <- NULL
  datac$ci <- NULL

  # Norm each subject's data
  ndata <- normDataWithin(data, idvar, measurevar, betweenvars, na.rm, .drop=.drop)

  # This is the name of the new column
  measurevar_n <- paste(measurevar, '_norm', sep='')

  # Collapse the normed data - now we can treat between and within vars the same
  ndatac <- summarySE(ndata, measurevar_n, groupvars=c(betweenvars, withinvars),
                      na.rm=na.rm, conf.interval=conf.interval, .drop=.drop)

  # Apply correction from Morey (2008) to the standard error and confidence interval
  #  Get the product of the number of conditions of within-S variables
  nWithinGroups    <- prod(vapply(ndatac[,withinvars, drop=FALSE], FUN=nlevels,
                           FUN.VALUE=numeric(1)))
  correctionFactor <- sqrt( nWithinGroups / (nWithinGroups-1) )

  # Apply the correction factor
  ndatac$sd <- ndatac$sd * correctionFactor
  ndatac$se <- ndatac$se * correctionFactor
  ndatac$ci <- ndatac$ci * correctionFactor

  # Combine the un-normed means with the normed results
  merge(datac, ndatac)
}

# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}

```

```{r read data}
emoapidata = read.table(file = './chi18-emoapi-faked-data.csv', header=TRUE, sep = ',')
```

```{r display data, echo=FALSE, results='asis'}
kable(head(emoapidata))
```

## Sampling
H1: ER accuracy will increase with the level of sampling using ER APIs (using api)

```{r summarizing the data : calm emotion}
emoapidataWithinCalm <- summarySEwithin(emoapidata, measurevar='calm', withinvars=c('emotionapi', 'imgfps'), idvar='imgfilename', na.rm=FALSE, conf.interval=.95)

emoapidataWithinJoy <- summarySEwithin(emoapidata, measurevar='joy', withinvars=c('emotionapi', 'imgfps'), idvar='imgfilename', na.rm=FALSE, conf.interval=.95)

emoapidataWithinSurprise <- summarySEwithin(emoapidata, measurevar='surprise', withinvars=c('emotionapi', 'imgfps'), idvar='imgfilename', na.rm=FALSE, conf.interval=.95)

emoapidataWithinOthers <- summarySEwithin(emoapidata, measurevar='others', withinvars=c('emotionapi', 'imgfps'), idvar='imgfilename', na.rm=FALSE, conf.interval=.95)
```

```{r drawing CI : calm emotion}
pd <- position_dodge(0.1) # move them .05 to the left and right

# calm
p1 <- ggplot(emoapidataWithinCalm, aes(x=imgfps, y=calm, colour=emotionapi, group=emotionapi)) + 
    geom_errorbar(aes(ymin=calm-ci, ymax=calm+ci), colour='black', width=.1, position=pd) +
    geom_line(position=pd) +
    geom_point(position=pd, size=3, shape=21, fill='white') + # 21 is filled circle
    xlab('Frame per second (fps)') +
    ylab('Emotion\'s value') +
    scale_colour_hue(name='ER APIs',    # Legend label, use darker colors
                     breaks=c('aws-rekognition', 'google-vision', 'ms-emotion'),
                     labels=c('AWS Rokognition', 'Google Vision', 'Microsoft Emotion'),
                     l=40) +                    # Use darker colors, lightness=40
    ggtitle('Calm') +
    expand_limits(y=0) +                        # Expand y range
    theme_bw() +
    theme(legend.justification=c(1,0), legend.position=c(1,0), , plot.title = element_text(hjust = 0.5))  

# surprise
p2 <- ggplot(emoapidataWithinSurprise, aes(x=imgfps, y=surprise, colour=emotionapi, group=emotionapi)) + 
    geom_errorbar(aes(ymin=surprise-ci, ymax=surprise+ci), colour='black', width=.1, position=pd) +
    geom_line(position=pd) +
    geom_point(position=pd, size=3, shape=21, fill='white') + # 21 is filled circle
    xlab('Frame per second (fps)') +
    ylab('Emotion\'s value') +
    scale_colour_hue(name='ER APIs',    # Legend label, use darker colors
                     breaks=c('aws-rekognition', 'google-vision', 'ms-emotion'),
                     labels=c('AWS Rokognition', 'Google Vision', 'Microsoft Emotion'),
                     l=40) +                    # Use darker colors, lightness=40
    ggtitle('Surprise') +
    expand_limits(y=0) +                        # Expand y range
    theme_bw() +
    theme(legend.justification=c(1,0), legend.position=c(1,0), , plot.title = element_text(hjust = 0.5))  

# joy
p3 <- ggplot(emoapidataWithinJoy, aes(x=imgfps, y=joy, colour=emotionapi, group=emotionapi)) + 
    geom_errorbar(aes(ymin=joy-ci, ymax=joy+ci), colour='black', width=.1, position=pd) +
    geom_line(position=pd) +
    geom_point(position=pd, size=3, shape=21, fill='white') + # 21 is filled circle
    xlab('Frame per second (fps)') +
    ylab('Emotion\'s value') +
    scale_colour_hue(name='ER APIs',    # Legend label, use darker colors
                     breaks=c('aws-rekognition', 'google-vision', 'ms-emotion'),
                     labels=c('AWS Rokognition', 'Google Vision', 'Microsoft Emotion'),
                     l=40) +                    # Use darker colors, lightness=40
    ggtitle('Joy') +
    expand_limits(y=0) +                        # Expand y range
    theme_bw() +
    theme(legend.justification=c(1,0), legend.position=c(1,0), , plot.title = element_text(hjust = 0.5))

# others
p4 <- ggplot(emoapidataWithinOthers, aes(x=imgfps, y=others, colour=emotionapi, group=emotionapi)) + 
    geom_errorbar(aes(ymin=others-ci, ymax=others+ci), colour='black', width=.1, position=pd) +
    geom_line(position=pd) +
    geom_point(position=pd, size=3, shape=21, fill='white') + # 21 is filled circle
    xlab('Frame per second (fps)') +
    ylab('Emotion\'s value') +
    scale_colour_hue(name='ER APIs',    # Legend label, use darker colors
                     breaks=c('aws-rekognition', 'google-vision', 'ms-emotion'),
                     labels=c('AWS Rokognition', 'Google Vision', 'Microsoft Emotion'),
                     l=20) +                    # Use darker colors, lightness=40
    ggtitle('Others') +
    expand_limits(y=0) +                        # Expand y range
    theme_bw() +
    theme(legend.justification=c(1,0), legend.position=c(1,0), , plot.title = element_text(hjust = 0.5)) 

grid.arrange(p1, p2, ncol = 2)

grid.arrange(p3, p4, ncol = 2)

```

